/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanceedu_common_data_HanceData */

#ifndef _Included_com_hanceedu_common_data_HanceData
#define _Included_com_hanceedu_common_data_HanceData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanceedu_common_data_HanceData
 * Method:    rsnew
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_HanceData_rsnew
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_common_data_HanceData
 * Method:    rsopen
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_HanceData_rsopen
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hanceedu_common_data_HanceData
 * Method:    rsdata
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_common_data_HanceData_rsdata
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hanceedu_common_data_HanceData
 * Method:    rsclose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_common_data_HanceData_rsclose
  (JNIEnv *, jobject);
  


#ifdef __cplusplus
}
#endif
#endif
