/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanceedu_memoryplan_Planer */

#ifndef _Included_com_hanceedu_memoryplan_Planer
#define _Included_com_hanceedu_memoryplan_Planer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hanceedu_memoryplan_Planer_MAXDAYS
#define com_hanceedu_memoryplan_Planer_MAXDAYS 400L
/*
 * Class:     com_hanceedu_memoryplan_Planer
 * Method:    create
 * Signature: ([BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_memoryplan_Planer_create
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_hanceedu_memoryplan_Planer
 * Method:    prepare
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_memoryplan_Planer_prepare
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_hanceedu_memoryplan_Planer
 * Method:    finishUnit
 * Signature: ([BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_memoryplan_Planer_finishUnit
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

/*
 * Class:     com_hanceedu_memoryplan_Planer
 * Method:    clear
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_memoryplan_Planer_clear
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
