/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanceedu_service_WtsService */

#ifndef _Included_com_hanceedu_service_WtsService
#define _Included_com_hanceedu_service_WtsService
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_hanceedu_service_WtsService
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hanceedu_service_WtsService_init
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_hanceedu_service_WtsService
 * Method:    voice
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hanceedu_service_WtsService_voice
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_hanceedu_service_WtsService
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_service_WtsService_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
