/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanceedu_data_HanceVoiceBook */

#ifndef _Included_com_hanceedu_data_HanceVoiceBook
#define _Included_com_hanceedu_data_HanceVoiceBook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nopenBook
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_nopenBook
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetStartingPage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetStartingPage
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetPageTotal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetPageTotal
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetStartingPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetStartingPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nopenPage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_data_HanceVoiceBook_nopenPage
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nclick
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_nclick
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetText
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetText
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetVoice
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetVoice
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetPicture
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetPicture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ncloseBook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_data_HanceVoiceBook_ncloseBook
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nreadWholeStart
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_nreadWholeStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nreadWholeContinue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_nreadWholeContinue
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ntestStart
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ntestStart
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ntestContinue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ntestContinue
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ntestClick
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ntestClick
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    nstopAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_data_HanceVoiceBook_nstopAll
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetBookName
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetBookName
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetBookCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetBookCode
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_data_HanceVoiceBook
 * Method:    ngetOpening
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_data_HanceVoiceBook_ngetOpening
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
