/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanceedu_common_data_SearchData */

#ifndef _Included_com_hanceedu_common_data_SearchData
#define _Included_com_hanceedu_common_data_SearchData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniNew
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_SearchData_jniNew
  (JNIEnv *, jobject);

/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniOpen
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_SearchData_jniOpen
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniGetQuestion
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_common_data_SearchData_jniGetQuestion
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniGetAnswer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_common_data_SearchData_jniGetAnswer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniGetPicture
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_hanceedu_common_data_SearchData_jniGetPicture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_hanceedu_common_data_SearchData
 * Method:    jniClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hanceedu_common_data_SearchData_jniClose
  (JNIEnv *, jobject);
  
  
JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_SearchData_jniGetSize
  (JNIEnv *, jobject, jint);
  
  JNIEXPORT jint JNICALL Java_com_hanceedu_common_data_SearchData_jniGetOffset
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
